language: python
python:
  - '3.5'
  - '3.6'
# dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -e .
script:
  - pytest
after_success:
  - codecov
